environment:
  nodejs_version: "16.9.1"

branches:
  only:
    - release

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm -g
  - npm install

build_script:
  - node_modules/.bin/electron-builder build --x64 --ia32
